---
- name: Install Python (if not already installed)
  raw: apt-get update && apt-get install -y python3
  become: true

- name: Install pip (if not already installed)
  become: true
  package:
    name: python3-pip

- name: Install required Python modules (pika)
  pip:
    name: pika
    state: present

- name: Copy script to target hosts
  copy:
    src: rabbitmq.py
    dest: /tmp/rabbitmq.py
    mode: 0755

- name: Run the script on target hosts
  command: >
    /usr/bin/python3 /tmp/rabbitmq.py
    --username "{{ rabbitmq_user }}"
    --password "{{ rabbitmq_password | regex_replace('\n', '') }}"
    --vhost "{{ rabbitmq_vhost }}"
  register: script_output

- name: Print message from playbook
  debug:
    msg: "{{ script_output.stdout }}"
