---

- name: Allow incoming traffic to RabbitMQ Admin Console
  become: true
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 15672
    jump: ACCEPT
    state: present

- name: Allow incoming traffic to RabbitMQ default port (localhost only)
  become: true
  iptables:
    chain: INPUT
    source: 127.0.0.1
    protocol: tcp
    destination_port: 5672
    jump: ACCEPT
    state: present
